name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY_FRONTEND: 818363358821.dkr.ecr.us-east-1.amazonaws.com/fe
  ECR_REPOSITORY_BACKEND: 818363358821.dkr.ecr.us-east-1.amazonaws.com/be

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Determine changed folder
        id: changed-folder
        run: echo "::set-output name=folder::$(git diff --name-only HEAD^..HEAD | grep -E 'frontend|backend' | cut -d'/' -f2 | sort -u)"

      - name: Build and push Docker image
        run: |
          if [ "${{ steps.changed-folder.outputs.folder }}" == "frontend" ]; then
            cd packages/frontend
            docker build -t frontend .
            docker tag frontend ${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
            docker push ${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          fi
          
          if [ "${{ steps.changed-folder.outputs.folder }}" == "backend" ]; then
            cd packages/backend
            docker build -t backend .
            docker tag backend ${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
            docker push ${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
          fi
