name: Other Changes Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'packages/react-frontend/**'
      - 'packages/express-backend/**'

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY_FRONTEND: 818363358821.dkr.ecr.us-east-1.amazonaws.com/fe
  ECR_REPOSITORY_BACKEND: 818363358821.dkr.ecr.us-east-1.amazonaws.com/be
  ECS_CLUSTER: test
  ECS_SERVICE_FRONTEND: fe
  ECS_SERVICE_BACKEND: be
  ECS_TASK_DEFINITION_FRONTEND: fe
  ECS_TASK_DEFINITION_BACKEND: be

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker images
        run: |
          cd packages/react-frontend
          docker build -t react-frontend .
          docker tag react-frontend ${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          docker push ${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}

          cd ../packages/express-backend
          docker build -t express-backend .
          docker tag express-backend ${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
          docker push ${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}

      - name: Update ECS task definitions
        run: |
          TASK_DEFINITION_FRONTEND=$(aws ecs register-task-definition \
            --region ${{ env.AWS_REGION }} \
            --family ${{ env.ECS_TASK_DEFINITION_FRONTEND }} \
            --container-definitions '[
              {
                "name": "frontend",
                "image": "'${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}'",
                "essential": true,
                "memory": 512
              }
            ]' \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text
          )

          TASK_DEFINITION_BACKEND=$(aws ecs register-task-definition \
            --region ${{ env.AWS_REGION }} \
            --family ${{ env.ECS_TASK_DEFINITION_BACKEND }} \
            --container-definitions '[
              {
                "name": "backend",
                "image": "'${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}'",
                "essential": true,
                "memory": 512
              }
            ]' \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text
          )

          echo "Updated ECS task definitions for frontend and backend: $TASK_DEFINITION_FRONTEND, $TASK_DEFINITION_BACKEND"

      - name: Update ECS services
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE_FRONTEND }} \
            --force-new-deployment

          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE_BACKEND }} \
